Use new colcon bundle version
aws-robotics/aws-robomaker-sample-application-deepracer pull request #19
Opened 2019-04-04 21:01 UTC by AAlon

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2019-04-04 21:14 UTC, ryanewel approved these changes

2019-04-04 21:17 UTC, ryanewel requested changes
Could you also update the README?

2019-04-04 21:28 UTC, ryanewel approved these changes

2019-04-04 23:43 UTC, timrobotson approved these changes

2019-04-11 17:28 UTC, timrobotson commented
Just rebased on master to get travis checks working correctly.

2019-04-17 00:09 UTC, merged